name: Logger
on:
  push:
    branches:
      - main

jobs:
  log:
    name: Log Message
    runs-on: ubuntu-latest
    env:
      MESSAGE: ${{ secrets.MESSAGE }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Log message
        run: |
          echo "Logging message..."
          echo "${{ env.MESSAGE }}"
          echo "${{ env.MESSAGE }}" > message.txt
          cat message.txt
